// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friends.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
WITH updated AS (
    UPDATE friend_requests
    SET status = 'accepted', responded_at = now()
    WHERE sender_id = $1 AND receiver_id = $2 AND status = 'pending'
    RETURNING sender_id, receiver_id
)
INSERT INTO friendships (user_id, friend_id)
SELECT LEAST(sender_id, receiver_id), GREATEST(sender_id, receiver_id)
FROM updated
`

type AcceptFriendRequestParams struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE (user_id = LEAST($1::int, $2::int) AND friend_id = GREATEST($1::int, $2::int))
)
`

type AreFriendsParams struct {
	UserID   int32 `json:"user_id"`
	FriendID int32 `json:"friend_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.UserID, arg.FriendID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const cancelFriendRequest = `-- name: CancelFriendRequest :exec
UPDATE friend_requests
SET status = 'cancelled', responded_at = now()
WHERE sender_id = $1 AND receiver_id = $2 AND status = 'pending'
`

type CancelFriendRequestParams struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) CancelFriendRequest(ctx context.Context, arg CancelFriendRequestParams) error {
	_, err := q.db.Exec(ctx, cancelFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const getFriendsOfUser = `-- name: GetFriendsOfUser :many
SELECT u.id, u.username, u.hashed_password, u.created_at
FROM friendships f
JOIN users u ON
    (f.user_id = $1 AND u.id = f.friend_id)
    OR (f.friend_id = $1 AND u.id = f.user_id)
`

func (q *Queries) GetFriendsOfUser(ctx context.Context, userID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getFriendsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingFriendRequest = `-- name: HasPendingFriendRequest :one
SELECT EXISTS (
  SELECT 1 FROM friend_requests
  WHERE
    status = 'pending'
    AND (
      (sender_id = $1 AND receiver_id = $2)
      OR
      (sender_id = $2 AND receiver_id = $1)
    )
)
`

type HasPendingFriendRequestParams struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) HasPendingFriendRequest(ctx context.Context, arg HasPendingFriendRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingFriendRequest, arg.SenderID, arg.ReceiverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT fr.id, fr.sender_id, fr.receiver_id, fr.status, fr.created_at, fr.responded_at, u.username AS sender_username
FROM friend_requests fr
JOIN users u ON fr.sender_id = u.id
WHERE fr.receiver_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type ListIncomingFriendRequestsRow struct {
	ID             int32            `json:"id"`
	SenderID       int32            `json:"sender_id"`
	ReceiverID     int32            `json:"receiver_id"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	RespondedAt    pgtype.Timestamp `json:"responded_at"`
	SenderUsername string           `json:"sender_username"`
}

// SELECT * FROM friend_requests
// WHERE receiver_id = $1 AND status = 'pending'
// ORDER BY created_at DESC;
func (q *Queries) ListIncomingFriendRequests(ctx context.Context, receiverID int32) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingFriendRequestsRow{}
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.SenderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT fr.id, fr.sender_id, fr.receiver_id, fr.status, fr.created_at, fr.responded_at, u.username AS receiver_username
FROM friend_requests fr
JOIN users u ON fr.receiver_id = u.id
WHERE fr.sender_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type ListOutgoingFriendRequestsRow struct {
	ID               int32            `json:"id"`
	SenderID         int32            `json:"sender_id"`
	ReceiverID       int32            `json:"receiver_id"`
	Status           string           `json:"status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	RespondedAt      pgtype.Timestamp `json:"responded_at"`
	ReceiverUsername string           `json:"receiver_username"`
}

// SELECT * FROM friend_requests
// WHERE sender_id = $1 AND status = 'pending'
// ORDER BY created_at DESC;
func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, senderID int32) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingFriendRequestsRow{}
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.ReceiverUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFriendRequest = `-- name: RejectFriendRequest :exec
UPDATE friend_requests
SET status = 'rejected', responded_at = now()
WHERE sender_id = $1 AND receiver_id = $2 AND status = 'pending'
`

type RejectFriendRequestParams struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) RejectFriendRequest(ctx context.Context, arg RejectFriendRequestParams) error {
	_, err := q.db.Exec(ctx, rejectFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const sendFriendRequest = `-- name: SendFriendRequest :exec
INSERT INTO friend_requests (sender_id, receiver_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SendFriendRequestParams struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) error {
	_, err := q.db.Exec(ctx, sendFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}
