// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	RoomID   *int32 `json:"room_id"`
	SenderID *int32 `json:"sender_id"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RoomID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadMessagesCount = `-- name: GetUnreadMessagesCount :one
SELECT COUNT(*) FROM messages m
LEFT JOIN message_reads mr ON m.id = mr.message_id AND mr.user_id = $2
WHERE m.room_id = $1 AND mr.message_id IS NULL
`

type GetUnreadMessagesCountParams struct {
	RoomID *int32 `json:"room_id"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) GetUnreadMessagesCount(ctx context.Context, arg GetUnreadMessagesCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadMessagesCount, arg.RoomID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.sender_id, m.content, m.created_at, u.username AS sender_username
FROM messages m
LEFT JOIN users u ON m.sender_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByRoomParams struct {
	RoomID *int32 `json:"room_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListMessagesByRoomRow struct {
	ID             int32            `json:"id"`
	RoomID         *int32           `json:"room_id"`
	SenderID       *int32           `json:"sender_id"`
	Content        string           `json:"content"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	SenderUsername *string          `json:"sender_username"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByRoomRow{}
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.SenderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
INSERT INTO message_reads (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkMessageReadParams struct {
	MessageID int32 `json:"message_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.MessageID, arg.UserID)
	return err
}
