// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendRequest struct {
	ID          int32            `json:"id"`
	SenderID    int32            `json:"sender_id"`
	ReceiverID  int32            `json:"receiver_id"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	RespondedAt pgtype.Timestamp `json:"responded_at"`
}

type Friendship struct {
	UserID    int32            `json:"user_id"`
	FriendID  int32            `json:"friend_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID        int32            `json:"id"`
	RoomID    *int32           `json:"room_id"`
	SenderID  *int32           `json:"sender_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Room struct {
	ID        int32            `json:"id"`
	Name      *string          `json:"name"`
	IsPrivate *bool            `json:"is_private"`
	CreatedBy *int32           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type RoomMember struct {
	RoomID   int32            `json:"room_id"`
	UserID   int32            `json:"user_id"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

type RoomRead struct {
	RoomID            int32            `json:"room_id"`
	UserID            int32            `json:"user_id"`
	LastReadMessageID *int32           `json:"last_read_message_id"`
	ReadAt            pgtype.Timestamp `json:"read_at"`
}

type User struct {
	ID             int32            `json:"id"`
	Username       string           `json:"username"`
	HashedPassword string           `json:"hashed_password"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
