// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: room_reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastMessageIDInRoom = `-- name: GetLastMessageIDInRoom :one
SELECT id
FROM messages
WHERE room_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLastMessageIDInRoom(ctx context.Context, roomID *int32) (int32, error) {
	row := q.db.QueryRow(ctx, getLastMessageIDInRoom, roomID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRoomReadForUser = `-- name: GetRoomReadForUser :one
SELECT room_id, user_id, last_read_message_id, read_at FROM room_reads
WHERE room_id = $1 AND user_id = $2
`

type GetRoomReadForUserParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetRoomReadForUser(ctx context.Context, arg GetRoomReadForUserParams) (RoomRead, error) {
	row := q.db.QueryRow(ctx, getRoomReadForUser, arg.RoomID, arg.UserID)
	var i RoomRead
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.ReadAt,
	)
	return i, err
}

const getUnreadMessages = `-- name: GetUnreadMessages :many
SELECT id, room_id, sender_id, content, created_at FROM messages m
WHERE m.room_id = $1
  AND m.id > COALESCE(
    (SELECT last_read_message_id FROM room_reads r WHERE r.room_id = $1 AND r.user_id = $2),
    0
  )
ORDER BY created_at ASC
`

type GetUnreadMessagesParams struct {
	RoomID *int32 `json:"room_id"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) GetUnreadMessages(ctx context.Context, arg GetUnreadMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getUnreadMessages, arg.RoomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoReadRoom = `-- name: GetUsersWhoReadRoom :many
SELECT user_id, last_read_message_id, read_at
FROM room_reads
WHERE room_id = $1
`

type GetUsersWhoReadRoomRow struct {
	UserID            int32            `json:"user_id"`
	LastReadMessageID *int32           `json:"last_read_message_id"`
	ReadAt            pgtype.Timestamp `json:"read_at"`
}

func (q *Queries) GetUsersWhoReadRoom(ctx context.Context, roomID int32) ([]GetUsersWhoReadRoomRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoReadRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWhoReadRoomRow{}
	for rows.Next() {
		var i GetUsersWhoReadRoomRow
		if err := rows.Scan(&i.UserID, &i.LastReadMessageID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoomRead = `-- name: UpsertRoomRead :exec
INSERT INTO room_reads (room_id, user_id, last_read_message_id, read_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (room_id, user_id)
DO UPDATE SET
  last_read_message_id = EXCLUDED.last_read_message_id,
  read_at = now()
`

type UpsertRoomReadParams struct {
	RoomID            int32  `json:"room_id"`
	UserID            int32  `json:"user_id"`
	LastReadMessageID *int32 `json:"last_read_message_id"`
}

func (q *Queries) UpsertRoomRead(ctx context.Context, arg UpsertRoomReadParams) error {
	_, err := q.db.Exec(ctx, upsertRoomRead, arg.RoomID, arg.UserID, arg.LastReadMessageID)
	return err
}
