// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, is_private, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, is_private, created_by, created_at
`

type CreateRoomParams struct {
	Name      *string `json:"name"`
	IsPrivate *bool   `json:"is_private"`
	CreatedBy *int32  `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.IsPrivate, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, is_private, created_by, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int32) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isUserInRoom = `-- name: IsUserInRoom :one
SELECT EXISTS (
    SELECT 1
    FROM room_members
    WHERE room_id = $1 AND user_id = $2
)
`

type IsUserInRoomParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) IsUserInRoom(ctx context.Context, arg IsUserInRoomParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRoom, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.username, rm.joined_at
FROM room_members rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1
`

type ListRoomMembersRow struct {
	ID       int32            `json:"id"`
	Username string           `json:"username"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID int32) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomMembersRow{}
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, is_private, created_by, created_at FROM rooms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
SELECT id, name, is_private, created_by, created_at FROM rooms
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserRoomsParams struct {
	CreatedBy *int32 `json:"created_by"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListUserRooms(ctx context.Context, arg ListUserRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listUserRooms, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomMemberParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	return err
}
