// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	RoomID   *int32 `json:"room_id"`
	SenderID *int32 `json:"sender_id"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RoomID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, is_private, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, is_private, created_by, created_at
`

type CreateRoomParams struct {
	Name      *string `json:"name"`
	IsPrivate *bool   `json:"is_private"`
	CreatedBy *int32  `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.IsPrivate, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password)
VALUES ($1, $2)
RETURNING id, username
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

type CreateUserRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, is_private, created_by, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int32) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadMessagesCount = `-- name: GetUnreadMessagesCount :one
SELECT COUNT(*) FROM messages m
LEFT JOIN message_reads mr ON m.id = mr.message_id AND mr.user_id = $2
WHERE m.room_id = $1 AND mr.message_id IS NULL
`

type GetUnreadMessagesCountParams struct {
	RoomID *int32 `json:"room_id"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) GetUnreadMessagesCount(ctx context.Context, arg GetUnreadMessagesCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadMessagesCount, arg.RoomID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             int32  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.HashedPassword)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.sender_id, m.content, m.created_at, u.username AS sender_username
FROM messages m
LEFT JOIN users u ON m.sender_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByRoomParams struct {
	RoomID *int32 `json:"room_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListMessagesByRoomRow struct {
	ID             int32            `json:"id"`
	RoomID         *int32           `json:"room_id"`
	SenderID       *int32           `json:"sender_id"`
	Content        string           `json:"content"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	SenderUsername *string          `json:"sender_username"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByRoomRow{}
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.SenderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.username, rm.joined_at
FROM room_members rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1
`

type ListRoomMembersRow struct {
	ID       int32            `json:"id"`
	Username string           `json:"username"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID int32) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomMembersRow{}
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, is_private, created_by, created_at FROM rooms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
INSERT INTO message_reads (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkMessageReadParams struct {
	MessageID int32 `json:"message_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.MessageID, arg.UserID)
	return err
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomMemberParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	return err
}
